### PR TITLE
update rush and pnpm. update copyright lint handling

### PR DESCRIPTION
**Pull request by calebmshafer**
Updating to a newer Rush and pnpm version in order to move to pnpm workspaces. This causes the copyright linter setup to be switched around to the new autoinstaller capability of Rush.

This makes this repo's version consistent with the iModel.js repo.

> Note: The repo will now require everyone to be using Node >12.17.0 for the new pnpm version.

### CODE REVIEW

**Review by aruniverse — APPROVED** [review]
lgtm

**Comment by aruniverse** [comment]
Wait, are we going to run into the same duplicate core deps issue like we had in the new viewer repo?
https://pnpm.io/how-peers-are-resolved

**Comment by calebmshafer** [comment]
@aruniverse gah you're right. I'll fix it :(

**Comment by aruniverse** [comment]
Going to close this in favor of #120

**Pull request closed without merging**
