### PR TITLE
modify the build-publish.yaml to separate rush version and rush publi…

### PR DESCRIPTION
**Pull request by jason-crow**
…sh steps

### CODE REVIEW

**Comment by aruniverse** [comment]
@jason-crow what was the need for this? its been a few months, so i dont expect you to remember. but i might close this if it deems unnecessary

**Comment by calebmshafer** [comment]
@aruniverse I think this was due to the issue with package.json ordering.

**Comment by aruniverse** [comment]
> @aruniverse I think this was due to the issue with package.json ordering.

what do you think, still needed?

**Comment by calebmshafer** [comment]
@aruniverse I think we're fine skipping this for now. We haven't hit the issue in a while :)

**Comment by jason-crow** [comment]
agreed, yeah I couldn't even recall the basis of this

**Pull request closed without merging**
